# Generated by Django 2.2.3 on 2019-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(blank=True, null=True, to='orders_items.OrderItem'),
        ),
    ]
