# Generated by Django 2.2.3 on 2019-07-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190712_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(blank=True, to='orders_items.OrderItem'),
        ),
    ]
