# Generated by Django 2.2.3 on 2019-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190712_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentOption',
            field=models.CharField(choices=[('MON', 'Dinheiro'), ('DEB', 'Cartão de Débito'), ('REF', 'Cartão Refeição')], max_length=4, verbose_name='Pagamento'),
        ),
    ]
