# Generated by Django 2.2.3 on 2019-07-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuId',
            new_name='menu',
        ),
    ]
