# Generated by Django 2.2.3 on 2019-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('deliveryEstimate', models.CharField(max_length=50, verbose_name='Tempo de Entrega')),
                ('imagePath', models.ImageField(upload_to='restaurant', verbose_name='Logo')),
                ('about', models.TextField(verbose_name='Sobre')),
                ('hours', models.CharField(max_length=100, verbose_name='Horas de Funcionamento')),
            ],
        ),
    ]
