# Generated by Django 2.2.3 on 2019-07-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190711_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Avaliação'),
        ),
    ]
