# Generated by Django 2.2.3 on 2019-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Avaliação')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
